FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get upgrade -y 
RUN apt-get install -y tzdata && \
    ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata

RUN apt-get install -y \
        g++ python3 python3-pip python3-opencv libmkl-rt

COPY bin/install-cuda.sh install-cuda.sh

RUN bash install-cuda.sh
